[package]
name = "turbo-cli"
version = "0.7.5"
edition = "2021"
rust-version.workspace = true

[[bin]]
name = "turbolang"
path = "src/main.rs"

[dependencies]
turbo-lexer = { path = "../turbo-lexer" }
turbo-ast = { path = "../turbo-ast" }
turbo-parser = { path = "../turbo-parser" }
turbo-codegen-cranelift = { path = "../turbo-codegen-cranelift" }
turbo-codegen-llvm = { path = "../turbo-codegen-llvm", optional = true }
turbo-sema = { path = "../turbo-sema" }
clap = { workspace = true }
ariadne = { workspace = true }
rustyline = "15"
notify = { workspace = true }
notify-debouncer-mini = { workspace = true }
ctrlc = { workspace = true }
libc = { workspace = true }

[features]
default = []
llvm = ["dep:turbo-codegen-llvm"]
