[package]
name = "turbo-codegen-cranelift"
version = "0.5.0"
edition = "2021"

[dependencies]
turbo-ast = { path = "../turbo-ast" }
cranelift = { workspace = true }
cranelift-jit = { workspace = true }
cranelift-module = { workspace = true }
cranelift-codegen = { workspace = true }
cranelift-frontend = { workspace = true }
cranelift-native = { workspace = true }
cranelift-object = { workspace = true }
target-lexicon = { workspace = true }

[dev-dependencies]
turbo-lexer = { path = "../turbo-lexer" }
turbo-parser = { path = "../turbo-parser" }
turbo-sema = { path = "../turbo-sema" }
