[package]
name = "turbo-codegen-cranelift"
version = "0.10.2"
edition = "2021"
rust-version.workspace = true
description.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
turbo-ast = { version = "0.10.2", path = "../turbo-ast" }
cranelift = { workspace = true }
cranelift-jit = { workspace = true }
cranelift-module = { workspace = true }
cranelift-codegen = { workspace = true }
cranelift-frontend = { workspace = true }
cranelift-native = { workspace = true }
cranelift-object = { workspace = true }
target-lexicon = { workspace = true }
serde_json = "1"
libc = "0.2"

[dev-dependencies]
turbo-lexer = { version = "0.10.2", path = "../turbo-lexer" }
turbo-parser = { version = "0.10.2", path = "../turbo-parser" }
turbo-sema = { version = "0.10.2", path = "../turbo-sema" }
