[package]
name = "turbo-formatter"
version = "0.9.2"
edition = "2021"
rust-version.workspace = true
description.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
turbo-lexer = { version = "0.9.2", path = "../turbo-lexer" }
turbo-parser = { version = "0.9.2", path = "../turbo-parser" }
