#!/usr/bin/env python3
"""Check package and release metadata that must move together.

This is intentionally dependency-free so it runs on macOS system Python,
GitHub-hosted runners, and release machines before a tag is pushed.
"""

from __future__ import annotations

import json
import os
import re
import subprocess
import tempfile
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent

# Homebrew formula template policy.
#
# The in-repo distribution/homebrew/turbo-lang.rb is NOT the formula users
# install — the authoritative formula (with real, verified sha256 values) is
# regenerated by .github/workflows/release.yml and pushed to the separate
# ZVN-DEV/homebrew-turbo tap at release time, because the real checksums are
# only known after the release artifacts are built. The in-repo copy is a
# mirror that can never carry trustworthy checksums.
#
# To keep that mirror honest rather than a stale/fake look-alike, we enforce a
# crisp two-state policy (network-free, so it runs on every CI pass):
#
#   * Template state (what this repo ships): the sha256 fields use the all-zero
#     sentinel below AND the formula carries HOMEBREW_TEMPLATE_MARKER, so the
#     placeholders are unmistakable and explained.
#   * Real state: every sha256 is non-placeholder well-formed hex and the marker
#     is absent (well-formedness is verified here; matching against published
#     artifacts would need network access we deliberately avoid in CI).
#
# Forbidden in-between states fail the check:
#   * placeholder shas with no marker  -> looks real but is fake (the BL-8 bug)
#   * marker present with real-looking shas -> "template" that could be mistaken
#     for verified checksums
PLACEHOLDER_SHA256 = "0" * 64
HOMEBREW_TEMPLATE_MARKER = "AUTHORITATIVE FORMULA LIVES IN THE ZVN-DEV/homebrew-turbo TAP"


class CheckFailure(Exception):
    pass


def read(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8")
    except FileNotFoundError as exc:
        raise CheckFailure(f"missing required file: {path.relative_to(REPO_ROOT)}") from exc


def rel(path: Path) -> str:
    try:
        return str(path.relative_to(REPO_ROOT))
    except ValueError:
        return str(path)


def package_version_from_cargo_toml(path: Path) -> str:
    in_package = False
    for line in read(path).splitlines():
        stripped = line.strip()
        if stripped == "[package]":
            in_package = True
            continue
        if in_package and stripped.startswith("[") and stripped.endswith("]"):
            break
        if in_package:
            match = re.match(r'version\s*=\s*"([^"]+)"', stripped)
            if match:
                return match.group(1)
    raise CheckFailure(f"{rel(path)} has no [package] version")


def workspace_readme_from_cargo_toml(path: Path) -> str:
    in_workspace_package = False
    for line in read(path).splitlines():
        stripped = line.strip()
        if stripped == "[workspace.package]":
            in_workspace_package = True
            continue
        if in_workspace_package and stripped.startswith("[") and stripped.endswith("]"):
            break
        if in_workspace_package:
            match = re.match(r'readme\s*=\s*"([^"]+)"', stripped)
            if match:
                return match.group(1)
    raise CheckFailure(f"{rel(path)} has no [workspace.package] readme")


def package_uses_workspace_readme(path: Path) -> bool:
    in_package = False
    for line in read(path).splitlines():
        stripped = line.strip()
        if stripped == "[package]":
            in_package = True
            continue
        if in_package and stripped.startswith("[") and stripped.endswith("]"):
            break
        if in_package and re.match(r"readme\.workspace\s*=\s*true\b", stripped):
            return True
    return False


def version_from_json(path: Path) -> str:
    try:
        data = json.loads(read(path))
    except json.JSONDecodeError as exc:
        raise CheckFailure(f"{rel(path)} is not valid JSON: {exc}") from exc
    version = data.get("version")
    if not isinstance(version, str) or not version:
        raise CheckFailure(f"{rel(path)} has no string version field")
    return version


def package_lock_root_version(path: Path) -> str:
    try:
        data = json.loads(read(path))
    except json.JSONDecodeError as exc:
        raise CheckFailure(f"{rel(path)} is not valid JSON: {exc}") from exc
    root_package = data.get("packages", {}).get("", {})
    version = root_package.get("version")
    if not isinstance(version, str) or not version:
        raise CheckFailure(f"{rel(path)} packages[''] has no string version field")
    return version


def homebrew_metadata(path: Path) -> tuple[str, list[str], list[str]]:
    text = read(path)
    version_match = re.search(r'^\s*version\s+"([^"]+)"', text, re.MULTILINE)
    if not version_match:
        raise CheckFailure(f"{rel(path)} has no formula version")
    urls = re.findall(r'^\s*url\s+"([^"]+)"', text, re.MULTILINE)
    sha256s = re.findall(r'^\s*sha256\s+"([0-9a-f]{64})"', text, re.MULTILINE)
    return version_match.group(1), urls, sha256s


def local_lock_versions(path: Path, package_names: set[str]) -> dict[str, str]:
    versions: dict[str, str] = {}
    current_name: str | None = None
    current_version: str | None = None

    def flush() -> None:
        if current_name in package_names and current_version is not None:
            versions[current_name] = current_version

    for line in read(path).splitlines():
        if line.strip() == "[[package]]":
            flush()
            current_name = None
            current_version = None
            continue
        name_match = re.match(r'name\s*=\s*"([^"]+)"', line.strip())
        if name_match:
            current_name = name_match.group(1)
            continue
        version_match = re.match(r'version\s*=\s*"([^"]+)"', line.strip())
        if version_match:
            current_version = version_match.group(1)
    flush()
    return versions


def require(condition: bool, message: str) -> None:
    if not condition:
        raise CheckFailure(message)


def extract_yaml_block_scalar(text: str, step_name: str) -> str:
    lines = text.splitlines()
    in_step = False
    in_run = False
    block: list[str] = []
    for line in lines:
        if line.startswith("      - name: "):
            if in_run:
                break
            in_step = line.strip() == f"- name: {step_name}"
            continue
        if in_step and line == "        run: |":
            in_run = True
            continue
        if in_run:
            if line.startswith("      - name: ") or (line.startswith("      - uses: ")):
                break
            if line.startswith("          "):
                block.append(line[10:])
            elif line.strip() == "":
                block.append("")
            else:
                break
    if not block:
        raise CheckFailure(f"release.yml step {step_name!r} has no run block")
    return "\n".join(block) + "\n"


def run_release_channel_classifier(script: str, tag: str) -> tuple[int, dict[str, str], str]:
    with tempfile.TemporaryDirectory() as tmp:
        output_path = Path(tmp) / "github_output"
        env = os.environ.copy()
        env["GITHUB_REF_NAME"] = tag
        env["GITHUB_OUTPUT"] = str(output_path)
        result = subprocess.run(
            ["bash", "-c", script],
            check=False,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
            env=env,
        )
        outputs: dict[str, str] = {}
        if output_path.exists():
            for line in output_path.read_text(encoding="utf-8").splitlines():
                if "=" in line:
                    key, value = line.split("=", 1)
                    outputs[key] = value
        return result.returncode, outputs, result.stdout + result.stderr


def check_release_channel_classifier(release_workflow: str) -> None:
    script = extract_yaml_block_scalar(release_workflow, "Classify release channel")
    stable_status, stable, stable_log = run_release_channel_classifier(script, "v0.16.0")
    require(stable_status == 0, f"stable release channel classifier failed: {stable_log.strip()}")
    require(
        stable == {"prerelease": "false", "make_latest": "true", "homebrew": "true"},
        f"stable release channel classifier produced wrong outputs: {stable}",
    )

    pre_status, prerelease, pre_log = run_release_channel_classifier(script, "v0.16.0-pre.1")
    require(pre_status == 0, f"prerelease channel classifier failed: {pre_log.strip()}")
    require(
        prerelease == {"prerelease": "true", "make_latest": "false", "homebrew": "false"},
        f"prerelease channel classifier produced wrong outputs: {prerelease}",
    )

    for tag in ["v0.16.0-rc.1", "v0.16.0-beta.2", "v0.16.0-alpha.1.build.7"]:
        status, outputs, log = run_release_channel_classifier(script, tag)
        require(status == 0, f"prerelease channel classifier failed for {tag}: {log.strip()}")
        require(
            outputs == {"prerelease": "true", "make_latest": "false", "homebrew": "false"},
            f"prerelease channel classifier produced wrong outputs for {tag}: {outputs}",
        )

    for tag in ["vnot-a-version", "v0.16", "0.16.0", "v0.16.0-", "v0.16.0+build.1"]:
        bad_status, _, _ = run_release_channel_classifier(script, tag)
        require(bad_status != 0, f"release channel classifier accepted malformed tag {tag}")


def tracked_files(repo_root: Path, pathspec: str) -> list[Path]:
    git_dir = repo_root / ".git"
    if not git_dir.exists():
        return []
    result = subprocess.run(
        ["git", "-C", str(repo_root), "ls-files", pathspec],
        check=False,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
    )
    if result.returncode != 0:
        raise CheckFailure(f"failed to list tracked files for {pathspec}: {result.stderr.strip()}")
    return [repo_root / line for line in result.stdout.splitlines() if line]


def check_benchmark_artifacts(repo_root: Path) -> None:
    allowed_suffixes = {
        ".c",
        ".go",
        ".js",
        ".md",
        ".py",
        ".rb",
        ".rs",
        ".sh",
        ".tb",
    }
    generated_dirs = {
        "c",
        "go",
        "js",
        "python",
        "ruby",
        "rust",
    }
    bad: list[str] = []
    for path in tracked_files(repo_root, "turbo/benchmarks"):
        rel_parts = path.relative_to(repo_root).parts
        if len(rel_parts) < 3 or rel_parts[0] != "turbo" or rel_parts[1] != "benchmarks":
            continue
        language_dir = rel_parts[2]
        if language_dir not in generated_dirs:
            continue
        if path.suffix not in allowed_suffixes:
            bad.append(rel(path))
    require(
        not bad,
        "tracked benchmark generated artifacts should be rebuilt from source, not committed: "
        + ", ".join(sorted(bad)),
    )


def check_release_consistency(repo_root: Path = REPO_ROOT) -> list[str]:
    passed: list[str] = []

    crate_manifests = sorted((repo_root / "turbo" / "crates").glob("*/Cargo.toml"))
    require(crate_manifests, "no crate manifests found under turbo/crates")

    workspace_readme = workspace_readme_from_cargo_toml(repo_root / "turbo" / "Cargo.toml")
    require(
        workspace_readme == "../README.md",
        f"turbo/Cargo.toml [workspace.package] readme should point at ../README.md, got {workspace_readme}",
    )
    crates_without_workspace_readme = [
        rel(manifest) for manifest in crate_manifests if not package_uses_workspace_readme(manifest)
    ]
    require(
        not crates_without_workspace_readme,
        "crate manifests should inherit workspace readme metadata: "
        + ", ".join(crates_without_workspace_readme),
    )
    passed.append("Cargo package README metadata is inherited by all crates")

    crate_versions = {manifest.parent.name: package_version_from_cargo_toml(manifest) for manifest in crate_manifests}
    unique_crate_versions = sorted(set(crate_versions.values()))
    require(
        len(unique_crate_versions) == 1,
        "crate versions differ: "
        + ", ".join(f"{name}={version}" for name, version in sorted(crate_versions.items())),
    )
    version = unique_crate_versions[0]
    passed.append(f"{len(crate_versions)} crate manifests agree on {version}")

    vscode_package = repo_root / "editors" / "vscode" / "turbo-lang" / "package.json"
    vscode_version = version_from_json(vscode_package)
    require(
        vscode_version == version,
        f"{rel(vscode_package)} version {vscode_version} does not match crate version {version}",
    )
    vscode_package_text = read(vscode_package)
    require('"license": "MIT"' in vscode_package_text, f"{rel(vscode_package)} does not declare MIT license")
    vscode_license = repo_root / "editors" / "vscode" / "turbo-lang" / "LICENSE"
    require(vscode_license.exists(), f"{rel(vscode_license)} is missing")
    passed.append(f"{rel(vscode_package)} version and license metadata match")

    vscode_lock = repo_root / "editors" / "vscode" / "turbo-lang" / "package-lock.json"
    vscode_lock_version = version_from_json(vscode_lock)
    vscode_lock_root = package_lock_root_version(vscode_lock)
    require(
        vscode_lock_version == version and vscode_lock_root == version,
        f"{rel(vscode_lock)} version drift: top={vscode_lock_version} root={vscode_lock_root} expected {version}",
    )
    passed.append(f"{rel(vscode_lock)} version matches")

    formula = repo_root / "distribution" / "homebrew" / "turbo-lang.rb"
    formula_version, urls, sha256s = homebrew_metadata(formula)
    require(formula_version == version, f"{rel(formula)} version {formula_version} does not match {version}")
    expected_targets = {
        "aarch64-apple-darwin",
        "x86_64-apple-darwin",
        "x86_64-unknown-linux-gnu",
    }
    expected_url_fragments = {f"turbolang-v{version}-{target}.tar.gz" for target in expected_targets}
    missing_url_fragments = [
        fragment for fragment in sorted(expected_url_fragments) if not any(fragment in url for url in urls)
    ]
    require(not missing_url_fragments, f"{rel(formula)} missing URLs for: {', '.join(missing_url_fragments)}")
    require(all(f"/releases/download/v{version}/" in url for url in urls), f"{rel(formula)} has URL tag drift")
    require(len(sha256s) == len(expected_targets), f"{rel(formula)} should have one sha256 per release target")
    formula_text = read(formula)
    require(
        'desc "Native compiled language with familiar syntax"' in formula_text,
        f"{rel(formula)} still overclaims Rust-level performance in its description",
    )
    require(
        f'assert_match "turbolang {version}"' in formula_text,
        f"{rel(formula)} test assertion does not check turbolang {version}",
    )
    require('bin.install "turbo-lsp"' in formula_text, f"{rel(formula)} does not require turbo-lsp install")
    require('bin.install "turbo-lsp" if' not in formula_text, f"{rel(formula)} still allows archives missing turbo-lsp")
    require('assert_predicate bin/"turbo-lsp", :exist?' in formula_text, f"{rel(formula)} does not test turbo-lsp")

    # Homebrew template policy: the in-repo mirror must never look like a real,
    # trustworthy formula while carrying fake checksums. See PLACEHOLDER_SHA256 /
    # HOMEBREW_TEMPLATE_MARKER above for the full rationale.
    has_placeholder_sha = any(sha == PLACEHOLDER_SHA256 for sha in sha256s)
    has_template_marker = HOMEBREW_TEMPLATE_MARKER in formula_text
    require(
        not (has_placeholder_sha and not has_template_marker),
        f"{rel(formula)} carries placeholder (all-zero) sha256 values but is not marked as a "
        f"non-authoritative template. Either populate real sha256 values, or add a header comment "
        f'containing "{HOMEBREW_TEMPLATE_MARKER}" so the placeholders cannot be mistaken for real checksums.',
    )
    if has_template_marker:
        real_looking = [sha for sha in sha256s if sha != PLACEHOLDER_SHA256]
        require(
            not real_looking,
            f"{rel(formula)} is marked a non-authoritative template but carries non-placeholder "
            f"sha256 values ({', '.join(real_looking)}). Template checksums must be the all-zero "
            f"sentinel so no one mistakes them for verified release checksums.",
        )
    formula_state = "non-authoritative template (all-zero sentinel shas, marked)" if has_template_marker else "real checksums"
    passed.append(f"{rel(formula)} version, URLs, and tests match; checksums are honest ({formula_state})")

    package_names = set(crate_versions)
    for lockfile in [repo_root / "turbo" / "Cargo.lock", repo_root / "turbo" / "fuzz" / "Cargo.lock"]:
        lock_versions = local_lock_versions(lockfile, package_names)
        if lockfile.name == "Cargo.lock" and lockfile.parent.name == "turbo":
            missing = sorted(package_names - set(lock_versions))
            require(not missing, f"{rel(lockfile)} missing local packages: {', '.join(missing)}")
        drift = {
            name: lock_version
            for name, lock_version in lock_versions.items()
            if lock_version != crate_versions[name]
        }
        require(
            not drift,
            f"{rel(lockfile)} has local package version drift: "
            + ", ".join(f"{name}={lock_version} expected {crate_versions[name]}" for name, lock_version in sorted(drift.items())),
        )
        passed.append(f"{rel(lockfile)} local package versions match")

    changelog = read(repo_root / "CHANGELOG.md")
    require(f"## [{version}]" in changelog, f"CHANGELOG.md has no section for {version}")
    passed.append("CHANGELOG.md has a section for the current version")

    release_workflow = read(repo_root / ".github" / "workflows" / "release.yml")
    require("turbolang turbo-lsp" in release_workflow, "release.yml does not package both turbolang and turbo-lsp")
    require("Smoke test - AOT build" in release_workflow, "release.yml is missing AOT release smoke")
    require("Classify release channel" in release_workflow, "release.yml does not classify stable vs prerelease tags")
    check_release_channel_classifier(release_workflow)
    require("prerelease: ${{ steps.release-channel.outputs.prerelease }}" in release_workflow, "release.yml does not route prerelease tags to GitHub prereleases")
    require("make_latest: ${{ steps.release-channel.outputs.make_latest }}" in release_workflow, "release.yml does not prevent prerelease tags from becoming Latest")
    require("steps.release-channel.outputs.homebrew == 'true'" in release_workflow, "release.yml does not restrict Homebrew updates to stable tags")
    require(
        "Native compiled language with familiar syntax" in release_workflow,
        "release.yml generated Homebrew formula still overclaims Rust-level performance",
    )
    require('bin.install "turbo-lsp"' in release_workflow, "release.yml generated Homebrew formula does not require turbo-lsp install")
    require('bin.install "turbo-lsp" if' not in release_workflow, "release.yml generated Homebrew formula still allows archives missing turbo-lsp")
    require('assert_predicate bin/"turbo-lsp", :exist?' in release_workflow, "release.yml generated Homebrew formula does not test turbo-lsp")
    passed.append("release workflow packages, smokes, classifies prereleases, and publishes the two-binary toolchain")

    nightly_workflow = read(repo_root / ".github" / "workflows" / "nightly.yml")
    require("cp turbo/target/release/turbolang turbo/target/release/turbo-lsp ." in nightly_workflow, "nightly.yml does not stage turbo-lsp")
    require('test -x ./turbo/target/release/turbo-lsp' in nightly_workflow, "nightly.yml does not verify turbo-lsp")
    passed.append("nightly workflow stages and verifies turbo-lsp")

    dockerfile = read(repo_root / "distribution" / "Dockerfile")
    require("-p turbo-cli -p turbo-lsp" in dockerfile, "Dockerfile does not build both CLI and LSP")
    require("/turbo-lsp /usr/local/bin/turbo-lsp" in dockerfile, "Dockerfile does not copy turbo-lsp")
    passed.append("Dockerfile builds and installs both binaries")

    installer = read(repo_root / "distribution" / "install.sh")
    require("install_binary turbolang" in installer, "install.sh does not install turbolang")
    require("install_binary turbo-lsp" in installer, "install.sh does not install turbo-lsp")
    require("release archive did not contain turbo-lsp" in installer, "install.sh does not reject archives missing turbo-lsp")
    require("installed CLI only" not in installer, "install.sh still allows CLI-only release archives")
    smoke = read(repo_root / "scripts" / "smoke_install_script.sh")
    require('test -x "${INSTALL_DIR}/turbolang"' in smoke, "installer smoke does not check turbolang")
    require('test -x "${INSTALL_DIR}/turbo-lsp"' in smoke, "installer smoke does not check turbo-lsp")
    require("BROKEN_STATUS" in smoke, "installer smoke does not test missing turbo-lsp failure")
    passed.append("installer and smoke fixture cover both binaries")

    release_docs = read(repo_root / "docs" / "RELEASE.md")
    require("./scripts/check_release_consistency.sh" in release_docs, "docs/RELEASE.md does not mention release consistency check")
    require(
        "./scripts/check_cargo_package_readiness.sh" in release_docs,
        "docs/RELEASE.md does not mention cargo package readiness check",
    )
    package_readiness = repo_root / "scripts" / "check_cargo_package_readiness.py"
    require(package_readiness.exists(), "missing scripts/check_cargo_package_readiness.py")
    package_readiness_sh = repo_root / "scripts" / "check_cargo_package_readiness.sh"
    require(package_readiness_sh.exists(), "missing scripts/check_cargo_package_readiness.sh")
    passed.append("release runbook includes consistency and package-readiness gates")

    check_benchmark_artifacts(repo_root)
    passed.append("benchmark comparison baselines are source-only")

    return passed


def write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def write_fixture(root: Path, version: str = "1.2.3") -> None:
    write(
        root / "turbo" / "Cargo.toml",
        '[workspace]\nmembers = ["crates/*"]\n\n[workspace.package]\nreadme = "../README.md"\n',
    )
    for name in [
        "turbo-ast",
        "turbo-cli",
        "turbo-codegen-cranelift",
        "turbo-formatter",
        "turbo-lexer",
        "turbo-lsp",
        "turbo-parser",
        "turbo-sema",
    ]:
        write(
            root / "turbo" / "crates" / name / "Cargo.toml",
            f'[package]\nname = "{name}"\nversion = "{version}"\nreadme.workspace = true\n',
        )

    write(
        root / "editors" / "vscode" / "turbo-lang" / "package.json",
        json.dumps({"version": version, "license": "MIT"}),
    )
    write(
        root / "editors" / "vscode" / "turbo-lang" / "package-lock.json",
        json.dumps(
            {
                "name": "turbo-lang",
                "version": version,
                "lockfileVersion": 3,
                "packages": {"": {"name": "turbo-lang", "version": version, "license": "MIT"}},
            }
        ),
    )
    write(root / "editors" / "vscode" / "turbo-lang" / "LICENSE", "MIT License\n")
    write(
        root / "distribution" / "homebrew" / "turbo-lang.rb",
        f'''class TurboLang < Formula
  desc "Native compiled language with familiar syntax"
  version "{version}"
  url "https://github.com/ZVN-DEV/Turbo-Language/releases/download/v{version}/turbolang-v{version}-aarch64-apple-darwin.tar.gz"
  sha256 "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
  url "https://github.com/ZVN-DEV/Turbo-Language/releases/download/v{version}/turbolang-v{version}-x86_64-apple-darwin.tar.gz"
  sha256 "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"
  url "https://github.com/ZVN-DEV/Turbo-Language/releases/download/v{version}/turbolang-v{version}-x86_64-unknown-linux-gnu.tar.gz"
  sha256 "cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc"
  def install
    bin.install "turbo-lsp"
  end
  test do
    assert_match "turbolang {version}", shell_output("#{{bin}}/turbolang --version")
    assert_predicate bin/"turbo-lsp", :exist?
  end
end
''',
    )
    lock_packages = "\n".join(
        f'[[package]]\nname = "{name}"\nversion = "{version}"\n'
        for name in [
            "turbo-ast",
            "turbo-cli",
            "turbo-codegen-cranelift",
            "turbo-formatter",
            "turbo-lexer",
            "turbo-lsp",
            "turbo-parser",
            "turbo-sema",
        ]
    )
    write(root / "turbo" / "Cargo.lock", f"version = 4\n\n{lock_packages}")
    fuzz_packages = "\n".join(
        f'[[package]]\nname = "{name}"\nversion = "{version}"\n'
        for name in [
            "turbo-ast",
            "turbo-codegen-cranelift",
            "turbo-formatter",
            "turbo-lexer",
            "turbo-parser",
            "turbo-sema",
        ]
    )
    write(root / "turbo" / "fuzz" / "Cargo.lock", f"version = 4\n\n{fuzz_packages}")
    write(root / "CHANGELOG.md", f"# Changelog\n\n## [{version}] - 2099-01-01\n")
    write(
        root / ".github" / "workflows" / "release.yml",
        '''jobs:
  release:
    steps:
      - name: Classify release channel
        id: release-channel
        env:
          GITHUB_REF_NAME: ${{ github.ref_name }}
        run: |
          set -euo pipefail
          VERSION="${GITHUB_REF_NAME#v}"
          if [[ ! "${GITHUB_REF_NAME}" =~ ^v[0-9]+\\.[0-9]+\\.[0-9]+(-[0-9A-Za-z][0-9A-Za-z.-]*)?$ ]]; then
            echo "error: release tags must look like vX.Y.Z or vX.Y.Z-pre.N; got ${GITHUB_REF_NAME}" >&2
            exit 1
          fi
          if [[ "${VERSION}" == *-* ]]; then
            echo "prerelease=true" >> "$GITHUB_OUTPUT"
            echo "make_latest=false" >> "$GITHUB_OUTPUT"
            echo "homebrew=false" >> "$GITHUB_OUTPUT"
          else
            echo "prerelease=false" >> "$GITHUB_OUTPUT"
            echo "make_latest=true" >> "$GITHUB_OUTPUT"
            echo "homebrew=true" >> "$GITHUB_OUTPUT"
          fi
      - name: Create Release
        with:
          prerelease: ${{ steps.release-channel.outputs.prerelease }}
          make_latest: ${{ steps.release-channel.outputs.make_latest }}
      - name: Update Homebrew tap
        if: success() && steps.probe-secrets.outputs.has_tap == 'true' && steps.release-channel.outputs.homebrew == 'true'
        run: |
          tar czf artifact.tgz turbolang turbo-lsp
          echo "Smoke test - AOT build"
          cat > Formula/turbo-lang.rb <<EOF
          class TurboLang < Formula
            desc "Native compiled language with familiar syntax"
            bin.install "turbo-lsp"
            assert_predicate bin/"turbo-lsp", :exist?
          end
          EOF
''',
    )
    write(
        root / ".github" / "workflows" / "nightly.yml",
        'cp turbo/target/release/turbolang turbo/target/release/turbo-lsp .\ntest -x ./turbo/target/release/turbo-lsp\n',
    )
    write(
        root / "distribution" / "Dockerfile",
        "RUN cargo build --release -p turbo-cli -p turbo-lsp\nCOPY --from=builder /build/turbo/target/release/turbo-lsp /usr/local/bin/turbo-lsp\n",
    )
    write(root / "distribution" / "install.sh", "install_binary turbolang\ninstall_binary turbo-lsp\nrelease archive did not contain turbo-lsp\n")
    write(root / "scripts" / "smoke_install_script.sh", 'test -x "${INSTALL_DIR}/turbolang"\ntest -x "${INSTALL_DIR}/turbo-lsp"\nBROKEN_STATUS=1\n')
    write(root / "scripts" / "check_cargo_package_readiness.py", "# fixture placeholder\n")
    write(root / "scripts" / "check_cargo_package_readiness.sh", "#!/usr/bin/env bash\n")
    write(root / "docs" / "RELEASE.md", "./scripts/check_release_consistency.sh\n./scripts/check_cargo_package_readiness.sh\n")


def run_self_test() -> int:
    with tempfile.TemporaryDirectory() as tmp:
        root = Path(tmp)
        write_fixture(root)
        check_release_consistency(root)

        formula = root / "distribution" / "homebrew" / "turbo-lang.rb"
        formula_clean = formula.read_text(encoding="utf-8")
        marker_comment = f"# {HOMEBREW_TEMPLATE_MARKER}; these shas are placeholders.\n"

        def zero_shas(text: str) -> str:
            return re.sub(r'sha256 "[0-9a-f]{64}"', f'sha256 "{PLACEHOLDER_SHA256}"', text)

        # Placeholder (all-zero) shas with no template marker must fail — this is
        # the BL-8 bug: a formula that looks real but carries fake checksums.
        formula.write_text(zero_shas(formula_clean), encoding="utf-8")
        try:
            check_release_consistency(root)
        except CheckFailure as exc:
            require("non-authoritative template" in str(exc), f"self-test expected placeholder-sha failure, got: {exc}")
        else:
            raise CheckFailure("self-test expected placeholder shas without a template marker to fail")

        # Template marker present but real-looking (non-placeholder) shas must fail.
        formula.write_text(marker_comment + formula_clean, encoding="utf-8")
        try:
            check_release_consistency(root)
        except CheckFailure as exc:
            require("non-placeholder" in str(exc), f"self-test expected marked-template real-sha failure, got: {exc}")
        else:
            raise CheckFailure("self-test expected a marked template with real shas to fail")

        # A marked template with the all-zero sentinel shas is the honest state — must pass.
        formula.write_text(zero_shas(marker_comment + formula_clean), encoding="utf-8")
        check_release_consistency(root)

        # Restore the clean fixture formula for the remaining mutations below.
        formula.write_text(formula_clean, encoding="utf-8")

        formula.write_text(formula.read_text(encoding="utf-8").replace("turbo-lsp", "missing-lsp", 1), encoding="utf-8")
        try:
            check_release_consistency(root)
        except CheckFailure as exc:
            require("turbo-lsp" in str(exc), f"self-test expected turbo-lsp failure, got: {exc}")
        else:
            raise CheckFailure("self-test expected mutated Homebrew formula to fail")

        workspace_manifest = root / "turbo" / "Cargo.toml"
        workspace_manifest.write_text(
            workspace_manifest.read_text(encoding="utf-8").replace('readme = "../README.md"', 'readme = "README.md"'),
            encoding="utf-8",
        )
        try:
            check_release_consistency(root)
        except CheckFailure as exc:
            require("[workspace.package] readme" in str(exc), f"self-test expected workspace readme failure, got: {exc}")
        else:
            raise CheckFailure("self-test expected wrong workspace readme metadata to fail")
        workspace_manifest.write_text(
            workspace_manifest.read_text(encoding="utf-8").replace('readme = "README.md"', 'readme = "../README.md"'),
            encoding="utf-8",
        )

        ast_manifest = root / "turbo" / "crates" / "turbo-ast" / "Cargo.toml"
        ast_manifest.write_text(
            ast_manifest.read_text(encoding="utf-8").replace("readme.workspace = true\n", ""),
            encoding="utf-8",
        )
        try:
            check_release_consistency(root)
        except CheckFailure as exc:
            require("workspace readme metadata" in str(exc), f"self-test expected readme metadata failure, got: {exc}")
        else:
            raise CheckFailure("self-test expected missing crate readme metadata to fail")

    with tempfile.TemporaryDirectory() as tmp:
        root = Path(tmp)
        write_fixture(root)
        subprocess.run(["git", "-C", str(root), "init"], check=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        write(root / "turbo" / "benchmarks" / "c" / "fib", "generated binary placeholder\n")
        write(root / "turbo" / "benchmarks" / "c" / "fib.c", "int main(void) { return 0; }\n")
        write(root / "turbo" / "benchmarks" / "js" / "fib.js", "console.log(1)\n")
        write(root / "turbo" / "benchmarks" / "go" / "fib", "generated binary placeholder\n")
        subprocess.run(
            [
                "git",
                "-C",
                str(root),
                "add",
                "turbo/benchmarks/c/fib",
                "turbo/benchmarks/c/fib.c",
                "turbo/benchmarks/js/fib.js",
                "turbo/benchmarks/go/fib",
            ],
            check=True,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
        )
        try:
            check_release_consistency(root)
        except CheckFailure as exc:
            require("tracked benchmark generated artifacts" in str(exc), f"self-test expected benchmark artifact failure, got: {exc}")
        else:
            raise CheckFailure("self-test expected tracked benchmark artifact to fail")

        subprocess.run(
            ["git", "-C", str(root), "rm", "--cached", "turbo/benchmarks/c/fib", "turbo/benchmarks/go/fib"],
            check=True,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
        )
        check_release_consistency(root)

    print("self-test: release consistency fixture checks passed")
    return 0


def main() -> int:
    if len(sys.argv) == 2 and sys.argv[1] == "--self-test":
        try:
            return run_self_test()
        except CheckFailure as exc:
            print(f"release consistency self-test failed: {exc}", file=sys.stderr)
            return 1
    if len(sys.argv) != 1:
        print("usage: check_release_consistency.py [--self-test]", file=sys.stderr)
        return 2

    try:
        passed = check_release_consistency()
    except CheckFailure as exc:
        print(f"release consistency check failed: {exc}", file=sys.stderr)
        return 1

    for item in passed:
        print(f"ok: {item}")
    print("release consistency check passed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
