[package]
name = "turbo-sema"
version = "0.10.1"
edition = "2021"
rust-version.workspace = true
description.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
turbo-ast = { version = "0.10.1", path = "../turbo-ast" }

[dev-dependencies]
turbo-lexer = { version = "0.10.1", path = "../turbo-lexer" }
turbo-parser = { version = "0.10.1", path = "../turbo-parser" }
